version: "3.7"

services:
  db:
    image: postgres:10
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: obd
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"
    volumes:
      - db_obd:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root -P root -d obd" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  db_obd:

